README.md, deploy/all_ns/operator.yaml, deploy/default_ns/operator.yaml
- Update project status from "pre-alpha" to "alpha".
- Update Docker image reference to Pravega org.
=> Release 0.1.0

README.md
Signed-off-by: Aparna <Aparna.Rr@emc.com>
1. Included TOC
=> issue 31: readme-doc

CONTRIBUTING.md
Signed-off-by: Aparna <Aparna.Rr@emc.com>
1. CONTRIBUTING.md included
2. Content included in wiki
https://github.com/pravega/zookeeper-operator/wiki/Contributing
=> issue 32: contributing.md

README.md
Signed-off-by: Aparna <Aparna.Rr@emc.com>
Build operator section was edited and replaced with content for `make build`
=> Issue 38 readme doc

Makefile
Zookeeper-Operator uses a customer Zookeeper image for the actual managed app, which includes certain scripts for startup, readiness, etc. This PR adds building/pushing this docker image to the CI process.
=> Add zookeeper app container to travis build

deploy/all_ns/rbac.yaml, deploy/default_ns/rbac.yaml
- fix rbac error in all_ns and default_ns
fix #50 
Deploy a zookeeper cluster using those files should work
=> Issue-50: fix rbac error

deploy/crds/zookeeper_v1beta1_zookeepercluster_crd.yaml
This updates ZookeeperCluster CRD description to be in line with JSON path.
=> Update ZookeeperCluster CRD description

docker/bin/zookeeperStart.sh
This patch addresses the issue https://github.com/pravega/zookeeper-operator/issues/132
During bootstrap observer nodes (nodes: 2,...) fail to register if kubernetes headless DNS fails to bootstrap fast enough.
This patch ensures that - in such cases - the dynamic config file is not written, allowing the instance to retry when the failed zk instance is restarted (e.g kubernetes reschedules the pod)
=> Issue 102: ZK Ensemble fails to bootstrap if headless domain DNS resolution is failing

charts/zookeeper-operator/Chart.yaml, charts/zookeeper-operator/values.yaml, charts/zookeeper/Chart.yaml, charts/zookeeper/values.yaml
**Purpose of the change:**
Fixes: #160
**What the code does:**
Updated appVersion and Chart version to latest stable verion
Signed-off-by: Gabor Kozma <gabo@kozmagabor.com>
=> Issue 160: Fix charts lint error and fixed version

charts/zookeeper-operator/templates/operator.yaml, charts/zookeeper-operator/templates/role.yaml, charts/zookeeper-operator/templates/rolebinding.yaml, charts/zookeeper-operator/templates/service_account.yaml, charts/zookeeper/templates/zookeeper.yaml
=> ISSUE-161 Helm chart lacks namespace fields on namespace scoped resources

docker/bin/zookeeperTeardown.sh
While scaling down the zk cluster, we are moving server entries from conf file first before the client connections are terminated. Due to that in reconcile we will get the error `server not found in ensemble`
Fixes #77
Changed the script such that server entries will get removed  from conf only after client connections are terminated.
Verified the following scenarios
1. Deleted pod
2. Scale down the replicas
3. Deleted zk  cluster. In all these scenarios, prestophook failure is not observed in kubectl events
=> Issue 77: Zookeeper pre-stop hook failes when cluster hasn't started

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This pr adds templates for pr and Issue. 
#195 
While creating a pr or issue it will create a sample format that the user can use to create description for them.
Try creating an issue or a pr a sample format should bee there.
=> Issue 195: Add GitHub issue and PR templates 

README.md, charts/zookeeper-operator/Chart.yaml, charts/zookeeper-operator/README.md, charts/zookeeper-operator/templates/_helpers.tpl, charts/zookeeper-operator/templates/operator.yaml, charts/zookeeper-operator/values.yaml, charts/zookeeper/Chart.yaml, charts/zookeeper/README.md, charts/zookeeper/templates/_helpers.tpl, charts/zookeeper/templates/post-install-upgrade-hooks.yaml, charts/zookeeper/values.yaml, deploy/crds/zookeeper_v1beta1_zookeepercluster_cr.yaml, pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go, pkg/apis/zookeeper/v1beta1/zookeepercluster_types_test.go
Updates the version number in the zookeeper operator and zookeeper charts.
=> Updating chart version

charts/zookeeper-operator/templates/operator.yaml, charts/zookeeper-operator/templates/post-install-upgrade-hooks.yaml, charts/zookeeper-operator/values.yaml
Operator chart: added nodeSelector, affinity and tolerations support
Adds support of scheduling parameters into operator chart.
Adds support of scheduling parameters into operator chart.
1. Add nodeSelector, affinity or tolerations into operator chart values
2. After installing operator chart, check that they are applied
=> Operator chart: added nodeselector, affinity and tolerations

pkg/apis/zookeeper/v1beta1/deepcopy_test.go, pkg/controller/zookeepercluster/zookeepercluster_controller_test.go, pkg/zk/generators_test.go
Increased unit test coverage
Fixes #235
Added more unit tests
Unit tests should pass
=> Issue 235: Increasing unit test coverage

Dockerfile, Makefile, docker/Dockerfile, docker/Dockerfile-swarm
Added fix to build docker images using local registry
Fixes #276
Added one  more argument DOCKER_REGISTRY to build
Verified that building using local registry image works
=> Issue 276: Added fix for building docker images using local registry

.github/workflows/ci.yaml, go.sum, pkg/test/e2e/e2eutil/zookeepercluster_util.go, test/e2e/basic_test.go, test/e2e/image_pullsecret_test.go, test/e2e/scale_test.go, test/e2e/zookeepercluster_test.go
Adding more end to end tests
Fixes #304
Added more tests for pull secret and admin service check
Tests should pass
=> Added more endtoend tests

docker/Dockerfile, docker/bin/zookeeperReady.sh, docker/bin/zookeeperStart.sh, docker/bin/zookeeperTeardown.sh
Changed the path of `zu.jar`
Fixes #342 
Changed the path from `/root` to `/opt/libs`
Verified operator upgrade  followed by cluster upgrade
=> Issue 342: Change the location of zu.jar in zookeeper Image

Dockerfile
Signed-off-by: Adi Muraru <amuraru@adobe.com>
Build using golang 1.16
Match the go build version with the one defined in go.mod
Fixes #380
=> Build using golang 1.16

charts/zookeeper-operator/Chart.yaml, charts/zookeeper-operator/README.md, charts/zookeeper-operator/values.yaml, charts/zookeeper/Chart.yaml, charts/zookeeper/README.md, charts/zookeeper/values.yaml, deploy/all_ns/operator.yaml, deploy/cr/ECS/zookeeper_v1beta1_zookeepercluster_cr.yaml, deploy/cr/pravega/zookeeper_v1beta1_zookeepercluster_cr.yaml, deploy/default_ns/operator.yaml, pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go, pkg/apis/zookeeper/v1beta1/zookeepercluster_types_test.go
Updating operator and cluster charts to `0.2.13`
Fixes #390
Update charts
Should be able to deploy using latest version of charts
=> Issue 390: Updating operator and cluster charts to latest version

api/v1beta1/zookeepercluster_types.go, api/v1beta1/zookeepercluster_types_test.go, charts/zookeeper-operator/Chart.yaml, charts/zookeeper-operator/README.md, charts/zookeeper-operator/values.yaml, charts/zookeeper/Chart.yaml, charts/zookeeper/README.md, charts/zookeeper/values.yaml, config/manager/manager.yaml, config/samples/ECS/zookeeper_v1beta1_zookeepercluster_cr.yaml, config/samples/pravega/zookeeper_v1beta1_zookeepercluster_cr.yaml
Updated Chart version to `0.2.14`
Fixes #472
Updated chart version
All e2e should pass
=> Issue 472: Updating chart version to 0.2.14

README.md, docker/Dockerfile, docker/zu/build.gradle.kts
Updates for Zookeeper 3.9.3
Bring in line with latest Zooper
=> Updates to Zookeeper
