pravega/zookeeper-operator

- example/cr-detailed.yaml
Mundane change.
I was using example/cr-detailed.yaml and it did not work. Found that the issue was that the sample value for spec.persistence.accessModes is incorrect.
> Fixup AccessMode in example/cr-detailed.yaml

- Makefile
- README.md
- cmd/exporter/main.go
- pkg/controller/zookeepercluster/zookeepercluster_controller.go
- pkg/yamlexporter/exportutil.go
The zookeeper exporter generates secondary resources YAML files.
./zookeeper-exporter -i ZookeeperCluster.yaml -o . 
```vinod@ubuntu:~/exporter_testing/ecs_exporter_yaml/Initial/ECSCluster/zk$ tree ZookeeperCluster/
ZookeeperCluster/
├── client
│   └── Service.yaml
├── config
│   └── ConfigMap.yaml
├── headless
│   └── Service.yaml
├── pdb
│   └── PodDisruptionBudget.yaml
└── zk
└── StatefulSet.yaml
```
> [FABRIC-7588] Added yaml exporter code into Zookeeper Operator

- pkg/version/version.go
We'd like to bump the version to `0.2.1` to release binaries for the latest YAML export feature, which uses the Zookeeper Operator to output YAML files of any secondary resources that _would_ be created by the operator, if it were running.
> Bump version to 0.2.1

- charts/zookeeper-operator/Chart.yaml
- charts/zookeeper-operator/templates/_helpers.tpl
- charts/zookeeper-operator/templates/clusterrole.yaml
- charts/zookeeper-operator/templates/clusterrolebinding.yaml
- charts/zookeeper-operator/templates/crd.yaml
- charts/zookeeper-operator/templates/operator.yaml
- charts/zookeeper-operator/templates/role.yaml
- charts/zookeeper-operator/templates/rolebinding.yaml
- charts/zookeeper-operator/templates/service_account.yaml
- charts/zookeeper-operator/values.yaml
- charts/zookeeper/Chart.yaml
- charts/zookeeper/templates/_helpers.tpl
- charts/zookeeper/templates/tests/clusterrole.yaml
- charts/zookeeper/templates/tests/clusterrolebinding.yaml
- charts/zookeeper/templates/tests/service_account.yaml
- charts/zookeeper/templates/tests/test.yaml
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
- Adding helm chart to deploy zookeeper-operator and zookeeper into Kubernetes cluster
- Implementing helm test to test successful deployment/upgrade of zookeeper cluster 
Fixes #80 
To deploy zookeper operator
`helm install charts/zookeeper-operator --name <zk-operator-release-name>`
To deploy zookeper cluster
`helm install charts/zookeeper --name <zk-release-name>`
To test the zookeeper cluster deployment/upgrade
`helm test <zk-release-name>`
If the zookeeper deployment/upgrade was successful and all pods are in Ready state then the test should pass, else it should fail.
> Issue 80: Adding Helm Charts for Zookeper deployment and testing

- docker/Dockerfile
Upgrates the Zookeeper image from 3.5.4-beta to 3.5.5
Fixes #82 
Ran the following tests successfully to validate that upgrading to the new image is compatible
- System Tests
- Longevity Tests
- Pravega Benchmark (ensured that we face no performance issues with the new image)
> Issue 82: Upgrading zookeeper image

- docker/zu/build.gradle
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
Changes the default image used to deploy zookeeper from `emccorp/zookeeper:3.5.4-beta-operator` to `pravega/zookeeper:0.2.3`
Fixes #85 
Deploy zookeeper in a cluster without specifying any image field in the manifest file.  When you describe the zookeeper pod, you should get the following value for the image field :
```
Containers:
zookeeper:
Container ID:  docker://9a5e0f63fb4d73ca617c884b50d6cce7dbd87b63234dceeabb7621e59dc8655f
Image:         pravega/zookeeper:0.2.3
```
> Issue 85: Setting appropriate default zookeeper image

- .travis.yml
- Dockerfile
- README.md
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>
Fixes #89  
Fix to change default zookeeper image deployed by zookeeper-operator to pravega/zookeeper:latest.
Updated go version for buidling zookeeper-operator to 1.12 in travis.yml
Updated go version in base image to 1.12.10 and also updated the Readme to reflect this.
The go version upgrade was needed to resolve a Windows cross compilation failure seen since last 2 days due to external changes to golang libraries.
> Issue-89: Fix windows cross compile error and zk default image

- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
When embedding the operator into another one, it complains because
the spec doesn't list this as an optional field (even though it is
but the CRDs don't show that!)
> spec: add omitempty to optional fields

- docker/bin/zookeeperReady.sh
- docker/bin/zookeeperStart.sh
- docker/bin/zookeeperTeardown.sh
- docker/zu/src/main/java/io/pravega/zookeeper/Zookeeper.kt
- pkg/controller/zookeepercluster/zookeepercluster_controller.go
- pkg/zk/generators.go
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>
Change log description
Changed zookeeper startup, shutdown and readiness scripts to deal with server restarts without invoking "reconfig".
Purpose of the change
Fixes #92
What the code does
Changes the way we handle zookeeper server restarts
TDB: Changes to Zookeeper-operator for handling permanent deletion of servers from zookeeper ensemble when we choose to scale down the zk cluster. For addition of new clusters to the ensemble (on scale up), that is already covered by the existing zookeeperStart.sh script.
How to verify it
All tests should pass.
Manually tested this on a 3 node zookeeper cluster.
Tried deleting all 3 nodes, one at a time and they came back up successfully.
Tried deleting 2 nodes at a time and they came back up …
> Issue 92: Zookeeper pods fail to restart when quorum not available

- README.md
Updates the README stating that the `version` field of the `ZookeeperCluster` should not be modified while an upgrade is in progress.
Fixes #95
> Issue 95: Documentation update to prevent version modification during an upgrade

- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/zk/generators.go
- pkg/zk/generators_test.go
Added dns annotation to zookeeper headless service that can be used to assign a dns name to the service.
Fixes #107 
Added `domainName` to the Zookeeper Cluster Spec, that can be set via manifest.
`FQDN for zookeeper headless service = serviceName.domainName.` ( ends with a . )
Added an annotation `external-dns.alpha.kubernetes.io/hostname` to the zookeeper headless service.
If domain name is not set in the manifest, this annotation is also not set.
1. In Zookeeper spec, set `domainName=example.com.`
2. **kubectl describe svc zookeeper-headless** should show :
```Annotations: external-dns.alpha.kubernetes.io/hostname: zookeeper-headless.example.com.```
> Issue 107: Allowing DNS annotations to be added to zookeeper headless service

- Makefile
- docker/Dockerfile-swarm
- docker/zoo.cfg.swarm
Created docker file to whitelist the `ruok` command. `netstat` got removed from `zookeeper:3.5.5` onwards.  Customised docker file will be used for docker swarm tests.
Fixes #122 
Signed-off-by: anisha.kj <anisha.kj@emc.com>
> Customised docker file for docker swarm

- charts/zookeeper-operator/Chart.yaml
- charts/zookeeper-operator/templates/crd.yaml
- charts/zookeeper-operator/values.yaml
- charts/zookeeper/Chart.yaml
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
- deploy/crds/zookeeper_v1beta1_zookeepercluster_crd.yaml
The additional printer column `Replicas` which is part of the Zookeeper Cluster CRD prints the value in `.Status.Replicas` field of the Zookeeper Cluster object which is incorrect. This value should be picked from the object Spec and not its Status.
Fixes #124 
Deployed the Zookeeper Cluster both using charts and manually and confirmed that value printed by the replicas field on doing `kubectl get zk` now prints the correct value.
> Issue 124: The additionalPrinterColumn of the Zookeeper Cluster "replicas" prints incorrect value

- pkg/zk/generators.go
Added CLUSTER_SIZE field in configmap
Fixes #137
upgrading zookeeper cluster from `0.2.5-rc0` to `0.2.6-rc0` is successful
> Issue137:  Zookeeper cluster upgrade is failing

- pkg/utils/zookeeper_util.go
Changed the ZK URL as <zk-name>-client is not resolved by operator if both are in different namespaces.
Fixes #139
Verified deployment, scale up/down in default and other namespaces
> Issue 139: Zookeeper operator is not updating cluster status correctly

- docker/bin/zookeeperStart.sh
Signed-off-by: anisha.kj anisha.kj@dell.com
In  minikube setup, for zookeeper-1 pod headless service is taking a while to come up and due to that nslookup was failing.  Added polling mechanism to check head less service is active.
Fixes #134 
Verified multiple times in minikube setup and able to deploy zookeeper  with 3 replicas.
> Issue134: Support zookeeper cluster setup on minikube

- cmd/manager/main.go
- deploy/all_ns/operator.yaml
- deploy/default_ns/operator.yaml
Change log description
Removed the readiness probe check from operator
Purpose of the change
Fixes #101
What the code does
Readiness probe check was preventing zk-operator to perform an upgrade. New pod is not becoming leader waiting for the readiness probe success and readiness probe check is not succeeding until it became leader, thus resulting in deadlock
Removed the readiness probe check from
deploy/all_ns/operator.yaml                                                                   
deploy/default_ns/operator.yaml
cmd/manager/main.go
How to verify it
Verified that able to upgrade operator versions.
> Issue 101: Zookeeper Operator upgrade fails because of readiness check in deploy file

- charts/zookeeper-operator/templates/clusterrole.yaml
Helm ClusterRole rules were out of date with the files generated in `deploy`.
> Sync helm chart RBAC with generated files

- charts/zookeeper-operator/templates/operator.yaml
- charts/zookeeper-operator/values.yaml
Change log description
Configured WATCH_NAMESPACE field in Helm charts.
Purpose of the change
Fixes #150
What the code does
Added new configuration param in values.yaml file, so that WATCH_NAMESPACE can be configured. Added new cluster roles in zookeeper-operator charts so that it can install zookeeper  in different name space ,other than the one in which operator is running.
How to verify it
Tried installing operator and zk in same and different namespace using charts.
> Issue150: Helm chart should allow watch namespace to be passed in.

- pkg/zk/generators.go
While creating the VolumeClaimTemplates for the Zookkeeper StatefulSet, the namespace of these PVCs is not explicitly set to that of the Zookkeeper Cluster.
Fixes #171 
Creates Zookkeeper VolumeClaimTemplates in the same namespace as the Zookkeeper Cluster
Created the zookeeper cluster in the namespace `new`.
Verified that the PVC is created in the same namespace as the zookeeper cluster
```
$ kubectl describe pvc data-zookeeper-0 -n new
Name:          data-zookeeper-0
Namespace:     new
StorageClass:  standard
Status:        Bound
Volume:        pvc-6b0f1880-550c-4f5c-8468-89a0ab1fdee9
Labels:        app=zookeeper
Annotations:   pv.kubernetes.io/bind-completed: yes
pv.kubernetes.io/bound-by-controller: yes …
```
> Issue 171: Create PVCs in cluster namespace

- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
- deploy/crds/zookeeper_v1beta1_zookeepercluster_cr.yaml
Updates the Zookeeper Operator charts.
Zookeeper Operator and zookeeper cluster should be deployed successfully both manually and using charts.
> Updating zookeeper charts

- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
We were not checking whether the persistence volume claim spec has a storage field, before setting the defaults. Due to that configured value was not taking effect
Fixes #177 
Added a check to ensure `storage` field value is empty before setting  deaults 
Verified by giving different values for storage in manifest file, and pvc are getting created accordingly. If storage is not specified pvcs are created with default size.
> Issue 177: Unable to configure storage resources of zookeeper PVCs

- README.md
- deploy/crds/zookeeper_v1beta1_zookeepercluster_cr.yaml
- deploy/crds/zookeeper_v1beta1_zookeepercluster_crd.yaml
- go.mod
- go.sum
- pkg/apis/zookeeper/v1beta1/status.go
- pkg/apis/zookeeper/v1beta1/status_test.go
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/controller/zookeepercluster/zookeepercluster_controller.go
- pkg/controller/zookeepercluster/zookeepercluster_controller_test.go
Signed-off-by: prabhaker24 <prabhaker.saxena@dell.com>
This PR introduces the cluster condition to the zookeeper cluster status which appropriately shows the State of a Zookeeper cluster in case of Pods Ready, Upgrade and Error state
To display the zookeeper cluster condition as part of the status field of the zookeeper cluster, which will fix #169 
1) It sets the cluster condition to Pods Ready, Upgrade, Error state
2) When all the pods of the zk sts are in ready state, in that case, it sets the pods ready condition to true
3) When the cluster is upgrading from one version to the other in that case it sets the upgrade condition to true
4) when the cluster is in upgrade failed state it sets the Error condition to true
5) Additionally, It sets the value of the current version in case of …
> Issue-169 Add version info to Zookeeper Cluster CR status

- README.md
- docker/Dockerfile
- docker/bin/zookeeperStart.sh
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/zk/generators.go
This PR adds support to enable `quorumListenOnAllIPs`. This config is required for Zookeeper to be able to run on an Istio based environment.
Some modification must be done in the zookeeperStartup script as well, since it uses `nslookup` to determine if the ZkServer is part of an ensemble or not. In case of Istio all the communication goes through the sidecar container which might not ready when the nslookup command issued. So we might need to wait a while to the sidecar to become ready. This script can be removed when Kubernetes 1.17 is more commonly used.
I also modified the Zookeeper docker container slightly, to add `curl`. Also I could not make the official 3.5.5 image work, I am guessing something wrong there, since it also does not work in a non Istio environment.
Fixes: #102
> Issue 102: Add support for ZK to be able to run on Istio enabled cluster

- docker/Dockerfile
- docker/bin/zookeeperTeardown.sh
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
Default Termination grace period was set to 30s, and in tearDown.sh we were waiting for 180s for client connection to terminate. Due to this after grace period is over, kubernetes is sending SIGKILL due to that we were getting `137` error code. (https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods)
Fixes #91 
Increased default termination grace period to 180s. In teardown script, corrected the  loop for waiting for client connection. Also installed `ps` in container, as zookeeper-3.5.5 doesnt have it.
Verified the following scenarios
1. Deleted pod
2. Scale down the replicas
3. Deleted zk  cluster. In all these scenarios, prestophook failure is not observed in kubectl events
> Issue 91: PrestopHook configured for zookeeper cluster always fails

- charts/zookeeper-operator/Chart.yaml
- charts/zookeeper-operator/README.md
- charts/zookeeper-operator/templates/crd.yaml
- charts/zookeeper-operator/values.yaml
- charts/zookeeper/Chart.yaml
- charts/zookeeper/README.md
- charts/zookeeper/templates/_helpers.tpl
- charts/zookeeper/templates/post-install-upgrade-hooks.yaml
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
- deploy/crds/zookeeper_v1beta1_zookeepercluster_cr.yaml
- deploy/crds/zookeeper_v1beta1_zookeepercluster_crd.yaml
- deploy/default_ns/rbac.yaml
Updates the charts and the the helm commands to work with helm v3. It makes all the cluster specs overridable through Helm values. Also adds self validating post-install and post-upgrade hooks to the charts.
Fixes #188 
Makes all cluster specs overridable and adds self-validating post-install and post-upgrade hooks to the charts.
User should be able to follow the instructions mentioned in the documentation to install/delete a zookeeper operator and zookeeper cluster using charts via helm v3. User should be able to modify any of the zookeeper cluster specs through the values.yaml file.
> Issue 188: Migration to helm v3, making cluster specs overridable and adding self-validating hooks

- docker/bin/zookeeperStart.sh
Signed-off-by: Daniel Gonçalves <daniel.dias.g@gmail.com>
The block code that detects and waits for the Envoy does not work because of the ```set -e line```.
The line ```SC=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:15000/ready)``` fails and the script stops running.
I fixed that by disable the flag in this block of code (simple fix).
Edit: format
> Issue 193: Fix envoy waiting block

- charts/zookeeper-operator/templates/service_account.yaml
- charts/zookeeper-operator/values.yaml
Adding the option `imagePullSecrets` inside the serviceAccount to allow for images in private registries. A list of secret names can be specified in `serviceAccount.imagePullSecrets`
> Added imagePullSecrets to serviceAccount for images in a private registry

- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types_test.go
With recent changes we have added metrics ports. While doing upgrade, metrics port is not set to a default value because in `withDefaults` we are only checking ports are not present. we were not checking for individual ports for client, quorum, leader-election and metrics are present. Due to this reconcile was failing.
Fixes #204
In case we have not specified all the ports in zookeeper cluster manifest,  in `withDefaults`  method, we will set the missing ports to default.
1. Verified zookeeper cluster status is set properly in case of upgrade
2. Verified by not giving client ports in the zk manifest, and client port is setting to default.
> Issue 204: ZK-operator does not add version to the CR status during upgrade

- docker/bin/zookeeperTeardown.sh
- pkg/apis/zookeeper/v1beta1/deepcopy_test.go
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
Reverted termination grace period to 30s , as it causes delay in upgrade and deletion of pods if there are client connections.
Fixes #206
Reverted termination grace period to 30s and teardown script, reduce the time for client connections to terminate from 180s to 30s
Verified that upgrade of pods is completing with in a minute.
> Issue 206: Zookeeper cluster upgrade is taking more time 

- charts/zookeeper-operator/templates/operator.yaml
- charts/zookeeper-operator/values.yaml
Fixes #202
Add default resources for operator pod and ability to override them.
_(Steps to verify that the changes are effective)_
> Add support for setting resources for operator pod

- README.md
- charts/zookeeper/values/minikube.yaml
Provides a sample manifest for a minikube environment would make it much easier for users to install a zookeeper cluster on minikube  with the required number of component replicas, resources and required options without having to override any of the values.
Fixes #217 
To install a cluster with the resource requirements that would work on a minikube environment, use the following command
```
helm install zookeeper charts/zookeeper --values charts/zookeeper/values/minikube.yaml
```
It will successfully install a zookeeper cluster with the required replicas, resources and options.
> Issue 217: Manifests for minikube installation using charts

- charts/zookeeper-operator/templates/post-install-upgrade-hooks.yaml
- charts/zookeeper-operator/values.yaml
* Adds a manifest which defines a post-install/upgrade hook to make sure the `zookeepercluster` resource exists.
* If one is unlucky with the timings when install the `zookeeper-operator` chart, directly followed by the `zookeeper` chart, the api-resource `ZooKeeperCluster` may not exist by the time the zookeeper chart tries to create a `ZooKeeperCluster`.
* See above.
Run many install/uninstall cycles of the mentioned charts -- see that the zookeeper chart does not start before its resource dependency is registered.
> ZooKeeper Operator API Resource Hook.

- pkg/controller/zookeepercluster/zookeepercluster_controller.go
- pkg/zk/generators.go
Currently, zookeeper exporter generates the  secondary resources( stateful set, pdb, config map, headless and cliene service) with owner reference set to primary resources . But the primary resource is not created by the exporter.  Due to this while creating the resources using the manifests generated by exporter it is failing.
Fixes #209
Removed the owner reference while creating headless service, client service, pdb, config map and stateful set
Verified  creating the zookeeper cluster using the yaml files generated by the exporter
Also verified zookeeper cluster deployment via operator
> Issue 209: Not able to create zookeeper cluster resources via exporter binary

- charts/zookeeper-operator/values.yaml
- cmd/manager/main.go
This patch extends the watch mechanism in operator so the ZookeeperCluster resources can be deployed in different namespaces than where the operator runs.
Fixes #142 
_(Steps to verify that the changes are effective)_
> Operator can watch a configurable set of namespaces

- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types_test.go
- pkg/utils/zookeeper_util.go
- pkg/zk/generators.go
- pkg/zk/generators_test.go
Instead of hard-coding "cluster.local" as the kubernetes cluster domain, this makes that setting configurable.
Analogous to this change I made to the Banzai Kafka Operator: https://github.com/banzaicloud/kafka-operator/pull/361
My cluster doesn't use `cluster.local` as our cluster domain, so DNS lookups were failing. Changing it to be configurable allows me to set it in the `ZookeeperCluster` object and successfully bring up a zookeeper cluster.
Adds a parameter to `ZookeeperCluster` called `kubernetesClusterDomain`, which, when set, is used everywhere in the code where `cluster.local` is currently used.
Kind of tricky if your cluster already works, but you could create a `ZookeeperCluster` with `kubernetesClusterDomain` set to something other than `cluster.local` and watch the cluster …
> Make kubernetes cluster domain configurable

- docker/bin/zookeeperStart.sh
We were copying zoo.cfg file from /conf directory to /data/conf.cfg only at the start. If any configuration parameters are changed after installation, it was not taking into effect.
Fixes #222
Modified the start up script such a way that /conf/zoo.cfg contents are copied to  /data/conf.cfg even on restart. Will retain the dynamicconfig file in /data/conf.cfg
Verified by changing the config parameters and saw that they are getting updated on rolling restarts.
> Issue 222: zoo.cfg updated parameters are not picked up during rolling restarts

- charts/zookeeper/README.md
- charts/zookeeper/values.yaml
- deploy/crds/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/apis/zookeeper/v1beta1/zz_generated.deepcopy.go
- pkg/zk/generators.go
Add image and volume array in the crd to support customize images deploy with zookeeper node.
Support multi images, issue: https://github.com/pravega/zookeeper-operator/issues/228
This code allows users to add customized images and volumes in the pod spec, which means users can deploy other containers with the zookeeper.
To support multi containers, add containers and volumes to the manifest
`
spec:
containers:
volumes:
`
Create a ZookeeperCluster CR and add another image to the containers and define the volume in the volumes, then apply the ZookeeperCluster CR, you will find the zookeeper instance with start with the images define in the containers.
> support mutli images

- docker/bin/zookeeperStart.sh
Fix is added to parse nslookup  output to differentiate lookup failure and DNS failure.
Fixes #240
In some scenarios, like DNS servers are not ready , nslookup  was fialing. In the code we were handling it for all the nodes except the first node. In case of DR , the node that is shutdown is the node containing `zookeeper-0`,  nslookup failure is causing split brain situation and it is creating a new cluster. 
Fix is added to parse the nslookup output and differentiate DNS failure vs lookup failure.
Verified, restart of of zookeeper pods, scale up and down.
In baremetal cluster deleted node containing zookeeper-0.
> Issue 240: Bootstrap Process does not handle missing DNS server correctly

- README.md
- charts/zookeeper-operator/README.md
- charts/zookeeper-operator/templates/operator.yaml
- charts/zookeeper/README.md
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
Adds the necessary checks to the zookeeper charts in order to set values for a subset of the options provided within a given block.
> Adding checks to helm charts

- charts/zookeeper/README.md
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
Does not specify any default value for storageclass which allows the default storageclass for the given environment to be picked instead of having to hard-code it.
Fixes #250 
Install the zookeeper charts which do not specify any value for the storageclass. The following command shows that the default storageclass for the environment will be automatically picked.
```
$ kubectl get storageclass
NAME                 PROVISIONER                                       AGE
nfs                  cluster.local/nfs-server-provisioner-1599805455   25d
standard (default)   kubernetes.io/vsphere-volume                      25d
$ kubectl get pvc
NAME                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES …
```
> Issue 250: Not specifying a default storageclass

- pkg/zk/generators.go
- pkg/zk/generators_test.go
> ISSUE-257 Propagate labels to ZookeeperCluster underlying resources

- pkg/zk/generators.go
- pkg/zk/generators_test.go
Signed-off-by: Oliver Maskery <oliver@wellplayed.games>
Pass annotations specified in ZookeeperCluster's Pod Policy to the StatefulSet's pod template.
Closes #125 
The ZookeeperClusterSpec already has a PodPolicy which contains an Annotations `map[string]string`, this PR simply passes it through into the constructed StatefulSet's pod template.
**Given** a ZookeeperCluster resource has annotations in its Spec.Pod.Annotations
**And** this resource is applied to a Kubernetes cluster
**When** the Zookeeper Operator reconciles the ZookeeperCluster resource
**Then** a StatefulSet is created
**And** the StatefulSet's Pod Template has the requested annotations
**And** the Pods created by the StatefulSet have the requested annotations
> Issue 125: Pass PodPolicy annotations from ZookeeperClusterSpec to StatefulSet Pod Templates.

- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
Fix marker comments for runtime object deepcopy.
The marker comments for runtime object deepcopy was wrongly located. As such, the runtime object deepcopy code was not generated via `operator-sdk generate k8s` as expected. This change fixes the issue.
Fix location of marker comments for runtime object deepcopy so that the deepcopy code gets generated correctly.
`operator-sdk generate k8s` should generate runtime object deepcopy code correctly.
> Fix marker comments for runtime object deepcopy

- charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- charts/zookeeper/README.md
- deploy/crds/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- go.mod
- go.sum
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/zk/generators.go
Added more zookeeper configuration options in zookeeper configmap.
Fixes #220, #224 
Added more options as part of zookeeper spec under config, so that users are able to configure these values
Able to set the configuration options, and pod should come up with the values set.
> Issue 220: Added support for more zookeeper configuration options

- charts/zookeeper-operator/values.yaml
- charts/zookeeper/README.md
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
Delete the old transaction logs by setting autopurge.Inerval to 1 hr in zookeeper configuration
Fixes #263
Set the default values of `autopurge.Inerval` to 1 hr. So that older snapshots got deleted automatically.
Verified that Purge Interval is set correctly from the zookeeper logs and older snapshots are getting deleted.
> Issue 263: Delete the old transaction logs from zookeeper

- charts/zookeeper-operator/Chart.yaml
- charts/zookeeper-operator/README.md
- charts/zookeeper/Chart.yaml
- charts/zookeeper/README.md
- deploy/all_ns/operator.yaml
- deploy/cr/ECS/zookeeper_v1beta1_zookeepercluster_cr.yaml
- deploy/cr/pravega/zookeeper_v1beta1_zookeepercluster_cr.yaml
- deploy/default_ns/operator.yaml
- test/e2e/multiple_zk_test.go
- test/e2e/upgrade_test.go
Signed-off-by: prabhaker24 <prabhaker.saxena@dell.com>
Helm chart version differs from pravega/charts
Fixes #265 
The ZooKeeper [operator] Helm charts provided in https://github.com/pravega/charts/tree/master/docs have recently been updated to version 0.2.9.
But the version in this repository is still 0.2.8:
https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/Chart.yaml
https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/Chart.yaml
it fixes the version in both locations to 0.2.9 
check both locations above in charts.yaml both has version set to 0.2.9.
> Issue-265-Helm chart version differs from pravega/charts

- charts/zookeeper/templates/zookeeper.yaml
Currently even when the storageType is set to ephemeral within the values.yaml, theephemeral configuration is not taking effect and the storageType of the deployed zookeeper cluster is getting set to persistence instead of ephemeral. 
Fixes #269 
Tested the following use-cases :
- Deployed zookeeper operator 0.2.9 and zookeeper cluster 0.2.9 with storageType = ephemeral
- Deployed zookeeper operator 0.2.9 and zookeeper cluster 0.2.9 with storageType = persistence
- Deployed zookeeper operator 0.2.8 and zookeeper cluster 0.2.8, upgraded the zookeeper cluster to 0.2.9 using reuse-values
- Deployed zookeeper operator 0.2.9 and zookeeper cluster 0.2.8, upgraded the zookeeper cluster to 0.2.9 using reuse-values
- Deployed zookeeper operator …
> Issue 269: Setting ephemeral storage type using charts

- charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- charts/zookeeper/README.md
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
- deploy/crds/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- go.mod
- go.sum
- pkg/apis/zookeeper/v1beta1/deepcopy_test.go
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/apis/zookeeper/v1beta1/zz_generated.deepcopy.go
- pkg/zk/generators.go
Added a new field annotations to persistence and populating while pvc is created
Fixes #165 
Provided support for adding annotations to PVCs
Created zookeeper cluster, by specifying annotations in values.yaml file. Annotations are populated for PVC created
> Issue 165: Adding annotations to PVC

- charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- charts/zookeeper/README.md
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
- deploy/crds/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- pkg/apis/zookeeper/v1beta1/deepcopy_test.go
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/apis/zookeeper/v1beta1/zz_generated.deepcopy.go
- pkg/zk/generators.go
Support for imagepullsecret added for allowing pull of images in a private repository.
Fixes #185 
imagepullsecret is added as part of pod policy and works with any other service account other than default  and allows to do pull for images from a private repository
Following is tested and works:-
1) zookeeper cluster deployment with the zookeeper image in a private repo works for a non-default service account when correct imagepullsecret is specified.
2) zookeeper cluster deployment with the zookeeper image in public repository works for both default and non-default service account.
> Issue 185: support for imagepullsecrets field added

- charts/zookeeper-operator/templates/operator.yaml
- charts/zookeeper-operator/values.yaml
Add support to add annotations to operator pod in helm chart
Ability to set custom annotations to pods
Extends helm chart
> Add support to add annotations to operator pod

- charts/zookeeper/templates/post-install-upgrade-hooks.yaml
The post-install-upgrade hook in zookeeper cluster charts currently does not verify that all desired replicas have been deployed.
Fixes #291 
The hook compares that the number of ready replicas is equal to the replica count mentioned within the spec, i.e. it checks that `.status.readyReplicas == .spec.replicas`
The zookeeper cluster deployment should succeed only when all the desired replicas have come to ready state.
> Issue 291: Fixing post-install-upgrade hook

- charts/zookeeper-operator/templates/pre-delete-hooks.yaml
- charts/zookeeper-operator/values.yaml
Provides a pre-delete hook which ensures that custom resources are deleted before deleting the operator.
Fixes #300 
Allows the operator to be deleted via helm only if the zookeepercluster custom resource has already been deleted, not otherwise.
- If you try to delete the zookeeper operator before having deleted the zookeeper cluster resource, the pre-delete job will fail, thereby not allowing the operator from being deleted.
- If you try to delete the zookeeper operator after the zookeeper cluster resource has been cleaned up successfully, the operator will also be successfully deleted.
> Issue 300: Zookeeper Operator pre-delete hook

- charts/zookeeper/templates/zookeeper.yaml
Fix Helm config spec cannot be set because the some paths are incorrect
Fixes #299 
Typos fixed
Changes in snapSizeLimitInKb, maxCnxns, maxClientCnxns, minSessionTimeout, maxSessionTimeout, autoPurgeSnapRetainCount should be applied to configMap and to zoo.cfg
> Issue 299: Fix incorrect paths in config spec

- pkg/controller/zookeepercluster/zookeepercluster_controller.go
- pkg/zk/generators.go
Add UID as a label for each PVC in `MakeStatefulSet` and list PVC using the UID in `getPVCList`.
Fix https://github.com/pravega/zookeeper-operator/issues/312.
- `MakeStatefulSet`: One more label, uid, when creating VolumeClaimTemplates
- `getPVCList`: List the PVC with the uid of the current ZookeeperCluster
- Normal PVC creation/deletion without node failures can still work
- As described in https://github.com/pravega/zookeeper-operator/issues/312, the reproduction steps will not trigger PVC deletion
> Issue 312: list PVC with ZookeeperCluster uid

- docker/bin/zookeeperStart.sh
When ensemble DOMAIN is not yet available (happens in k8s when svc domain dns resolve is slow to resolve), observer peers (id>=2) fail to register and enter a crash loop.
Previously the DYNCONFIG was populated with peer nodes but `REGISTER_NODE` is false (domain not yet available) hence the `zu add` never called. Subsequently when peer is restarted the registration is never called
Fixes  #315
DYNCONFIG is not updated, if ensemble is not available for pods starting from ID 2  
Verified that second zookeeper pod is starting successfully.
> Observers fail to register when zk ensemble service domain is not yet available

- charts/zookeeper-operator/Chart.yaml
- charts/zookeeper-operator/README.md
- charts/zookeeper-operator/values.yaml
- charts/zookeeper/Chart.yaml
- charts/zookeeper/README.md
- charts/zookeeper/values.yaml
- deploy/all_ns/operator.yaml
- deploy/cr/ECS/zookeeper_v1beta1_zookeepercluster_cr.yaml
- deploy/cr/pravega/zookeeper_v1beta1_zookeepercluster_cr.yaml
- deploy/default_ns/operator.yaml
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types_test.go
Updates the zookeeper and zookeeper operator version within the charts and the manifest files
Fixes #322 
Changes the default version of the zookeeper operator and zookeeper cluster to 0.2.10
Should deploy the latest version of zookeeper operator as well as zookeeper cluster i.e. 0.2.10
> Issue 322: Updating charts to latest version

- charts/zookeeper-operator/templates/pre-delete-hooks.yaml
- charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- Add the capability to install the chart in eks versions that don't support apiVersion=apiextensions.k8s.io/v1beta1 anymore
Closes #329 
The code is using .Capabilities.APIVersions.Has to check for the apiVersion apiextensions.k8s.io/v1, if it finds it it uses to create the CRD, if it doesn't it falls back to apiextensions.k8s.io/v1beta1
You are able to install the chart with the CRD in eks v1.19.0 version from which apiextensions.k8s.io/v1beta1 was removed
> Issue 329: CRD apiVersion check

- pkg/zk/generators.go
1. Fix Pod SecurityContext config error in ZK charts
Close #333 
1. Fix Pod SecurityContext config error in ZK charts
Create a ZK CR with  Pod.SecurityContext  config, then check the created ZK StatufulSet config if contained 
correct Pod.SecurityContext
> Issue 333: Fix Pod SecurityContext config error in ZK charts

- charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- charts/zookeeper/README.md
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
- deploy/crds/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- pkg/apis/zookeeper/v1beta1/deepcopy_test.go
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/apis/zookeeper/v1beta1/zz_generated.deepcopy.go
- pkg/zk/generators.go
- pkg/zk/generators_test.go
Adding support for init containers
Fixes #332
Add new spec field for init container and attach to the podspec if specified
Verify that  zookeeper pods are coming up with init containers and the commands mentioned in init containers are executed successfully
> Issue 332: Add support for init containers in zookeeper pods

- pkg/controller/zookeepercluster/zookeepercluster_controller.go
- pkg/controller/zookeepercluster/zookeepercluster_controller_test.go
The PR makes the following changes:
- label the current RV of the zookeeperCluster to the sts when creation
- check whether the current RV of the zookeeperCluster is larger than the RV labeled to the sts before updating the sts
Fixes #314
> fix issue-314 by checking zookeeperCluster resource version before updating sts

- charts/zookeeper-operator/README.md
- charts/zookeeper-operator/templates/_helpers.tpl
- charts/zookeeper-operator/templates/operator.yaml
- charts/zookeeper-operator/values.yaml
Adding sidecar features to zookeeper-operator
Fixes #345 
Integrate. and enable the Sidecars with zookeeper-operator
Enable and. configure volumes and environment variables required for sidecars.
1.Helm lint.
2.Update the .Values with Any Sidecar containers.
3.By adding required additional volumes and Environment variables.
4.helm template.
> Adding sidecar feature to zookeeper-operator

- charts/zookeeper-operator/Chart.yaml
- charts/zookeeper-operator/README.md
- charts/zookeeper-operator/values.yaml
- charts/zookeeper/Chart.yaml
- charts/zookeeper/README.md
- charts/zookeeper/values.yaml
- deploy/all_ns/operator.yaml
- deploy/cr/ECS/zookeeper_v1beta1_zookeepercluster_cr.yaml
- deploy/cr/pravega/zookeeper_v1beta1_zookeepercluster_cr.yaml
- deploy/default_ns/operator.yaml
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types_test.go
Updates the zookeeper and zookeeper operator version within the charts and the manifest files
Fixes #346 
Changes the default version of the zookeeper operator and zookeeper cluster to 0.2.11
Should deploy the latest version of zookeeper operator as well as zookeeper cluster i.e. 0.2.11
> Issue 346: Updating charts to latest version

- charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml
Added sub resource field in CRD version `v1`
Fixes #350
Modified CRD to update subresources
Verify that `kubectl get zk` is showing the fields correctly. Also verify the output of `kuectl describe zk zookeeper`
> Issue 350: ZookeeperCluster crd's status disappear

- pkg/controller/zookeepercluster/zookeepercluster_controller.go
Fix owner-rv check by checking the existing STS object
Previously the owner-rv label was looked up in the wrong object
Fixes #314
> fix issue-314 by checking zookeeperCluster resource version before updating sts ADDENDUM

- charts/zookeeper-operator/templates/_helpers.tpl
- charts/zookeeper-operator/templates/operator.yaml
Wrapped additionalSidecars and additionalVolumes inside named templates.
Allows for defining templates for additionalSidecars/Volumes by extending the zookeeper-operator helm chart and overwriting `chart.*`.
Fixes  https://github.com/pravega/zookeeper-operator/issues/358
> Added option to define templates for additional sidecars and volumes

- deploy/all_ns/rbac.yaml
- deploy/default_ns/rbac.yaml
Rbac clusterrole  add service accounts authorization.
Fix #361
> Fix rbac cluster role

- pkg/controller/zookeepercluster/zookeepercluster_controller.go
- pkg/controller/zookeepercluster/zookeepercluster_controller_test.go
When upgrading the operator and the ZookeeperCluster and StatefulSet are already
created, the sts owner-rv is not set (it is set once when the sts is created)
Handle this upgrade scenario and set the owner-rv label on sts once when this is not set
Fixes #314
> fix issue-314 by checking zookeeperCluster resource version before updating sts ADDENDUM-2

- pkg/controller/zookeepercluster/zookeepercluster_controller.go
In ClearUpgradeStatus() function, we were not updating the zookeeper cluster, only the status was getting updated 2 times. Due to that again we try to update the cluster, was getting error as below.
, ```Operation cannot be fulfilled on zookeeperclusters.zookeeper.pravega.io \"zookeeper\": the object has been modified; please apply your changes to the latest version and try again"```  
_Fixes #357
Update the cluster instance correctly
Verify that during upgrade of zookeeper cluster, error messages are not coming frequently in operator logs.
> Issue 357: Fix for error messages coming in operator logs

- charts/zookeeper-operator/templates/_crd_openapiv3schema.tpl
helm install fails to install the new CRD in k8s 1.15
Fixing by reverting to using helm conditional on these old versions
> Add generate Makefile target to generate operator-sdk resources ADDENDUM

- charts/zookeeper-operator/templates/_crd_openapiv3schema.tpl
Fix issue in CRD
Change log description
helm install fails to install the new CRD in k8s 1.15
Fixing by reverting to using helm conditional on these old versions
Fixes #363
Fixed the CRD 
Verified operator and cluster install works fine
> Issue 363: Fixing CRD to work with k8 1.15 version

- charts/zookeeper-operator/Chart.yaml
- charts/zookeeper-operator/README.md
- charts/zookeeper-operator/values.yaml
- charts/zookeeper/Chart.yaml
- charts/zookeeper/README.md
- charts/zookeeper/values.yaml
- deploy/all_ns/operator.yaml
- deploy/cr/ECS/zookeeper_v1beta1_zookeepercluster_cr.yaml
- deploy/cr/pravega/zookeeper_v1beta1_zookeepercluster_cr.yaml
- deploy/default_ns/operator.yaml
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go
- pkg/apis/zookeeper/v1beta1/zookeepercluster_types_test.go
Updates the zookeeper and zookeeper operator version within the charts and the manifest files
Fixes #371 
Changes the default version of the zookeeper operator and zookeeper cluster to 0.2.12
Should deploy the latest version of zookeeper operator as well as zookeeper cluster i.e. 0.2.12
> Issue 371: Updating charts  to latest version

- go.mod
- go.sum
See: https://github.com/advisories/GHSA-c72p-9xmj-rx3w
Fixes https://github.com/pravega/zookeeper-operator/issues/375
> Fix containerd CVE-2021-32760

- .codecov.yml
Added codecov.yml file for setting code coverage targets
Fixes #148
Configuring codecov for PR validation tasks
Verify codecov configuration is taking effect
> Issue 148: Configuring codecov for PR validation tasks

- .github/workflows/ci.yaml
- Makefile
Currently publishing docker images of zookeeper-operator/zookeeper are manual
Fixes #266
Publish images to docker hub when a new release is made
_(Steps to verify that the changes are effective)_
> Issue 266: Automating the release process 

- docker/bin/zookeeperFunctions.sh
- docker/bin/zookeeperReady.sh
- docker/bin/zookeeperStart.sh
The nslookup only exit with status 0 with successful lookup of dns record for both forward and backward lookups. It would mean that the cluster's DNS setup has to support. `getent` only performs a forward lookup.
pravega#76
> Use getent instead of nslookup for starting scripts

- pkg/controller/zookeepercluster/zookeepercluster_controller.go
Prevents the operator from reconciling every time it updates the status. 
Fixes #389 
I noticed in the logs that the reconcile loop was running none stop, some times with only a few milisecond pauses. In my own operators I have had the same problem with updating the status object triggering a loop, if you use a predicate to filter events you can prevent that from happening. The build in [predicate.GenerationChangedPredicate{}](https://github.com/operator-framework/operator-sdk/blob/v0.19.4/pkg/predicate/predicate.go#L39) does a good job at preventing that and still allowing through other changes. 
Start up the operator, create a cluster and it should reconcile once every 30seconds.
> Prevent status updates from triggering reconcile loops

- charts/zookeeper/templates/post-install-upgrade-hooks.yaml
- charts/zookeeper/values.yaml
Signed-off-by: Petr Kohut <petr.kohut@williamhill.co.uk>
- Adds an option to add pod annotations to the zookeeper-post-install-upgrade K8s job.
Fixes #394 
- adds additional property into values.yaml allowing to set pod annotations on post-install-upgrade job
- updates the K8s manifest of post-install-upgrade Job
```sh
helm template test . --set hooks.pod.annotations.test=hello
```
> Issue 394: Allow to set pod annotations in post-install-upgrade job in helm chart

- charts/zookeeper-operator/README.md
- charts/zookeeper-operator/templates/operator.yaml
- charts/zookeeper-operator/values.yaml
- cmd/manager/main.go
- pkg/controller/config/config.go
- pkg/controller/zookeepercluster/zookeepercluster_controller.go
- pkg/controller/zookeepercluster/zookeepercluster_controller_test.go
add DisableFinalizer config and skip adding zkFinalziers when set it to true.
Issue-400
skip adding zkFinalziers when DisableFinalizer set to true.
Set disableFinalizer to true in values and deploy zookeeper operator, the deployed zookeeper  clusters should have the finalizers as empty.And when delete operator before deleting zookeeper  clusters, zk cluster deletion will not be blocked.
> [Issue-400] add disableFinalizer flag

- charts/zookeeper-operator/templates/pre-delete-hooks.yaml
Signed-off-by: Darren Lau <panyuenlau@gmail.com>
Add missing namespaces to the resources in pre-delete-hooks.yaml within the zookeeper-operator chart
Fixes #411
This PR adds the `namespace` field to the resources in the pre-delete-hooks.yaml
The programmatic way (as described in the issue) of uninstalling the zookeeper-operator would have all the pre-delete-hooks resources created in the namespace that the helm release uses, and the uninstallation works fine
> Add missing namespaces to pre-delete-hooks.yaml in zookeeper-operator chart

- charts/zookeeper/templates/post-install-upgrade-hooks.yaml
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
Added more validations in zookeeper post install hook.
Also changed the `preallocsize` to `16MB` in values files, to reduce transactional log size.
Fixes #417
Added more validations in post install hook, so that hook will succeed only after all the zookeeper pods are ready.
Verified zookeeper cluster installation
> Issue 417: Harden zookeeper post-install hook

- charts/zookeeper-operator/README.md
Update zookeeper-operator Helm configuration documentation.
Fixes #421 
Updates the `charts/zookeeper-operator/README.md` to reflect all the Helm configuration parameters for the zookeeper-operator chart.
_(Steps to verify that the changes are effective)_
> docs: Update zookeeper-operator helm configuration docs

- charts/zookeeper-operator/templates/clusterrole.yaml
- charts/zookeeper-operator/templates/clusterrolebinding.yaml
Removes metadata.namespace from non-namespaced resources such as ClusterRole and ClusterRoleBinding.
Fixes #430 
Removes `metadata.namespace` from non-namespaced resources
> Issue 430: remove namespace from non-namespaced resources

- README.md
- docker/Dockerfile
- docker/zu/build.gradle.kts
Fixes: #433
Update zookeeper version to 3.7.0 - as 0.3.8 got released bumped version to it.
Bring latest fixes
Fixes: #433
Tested with locally build image (using make build-zk-image)
> Update zk version to 3.8.0

- Makefile
- README.md
- api/v1beta1/zookeepercluster_types.go
- charts/zookeeper-operator/templates/_crd_openapiv3schema.tpl
- charts/zookeeper/README.md
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
- config/crd/bases/zookeeper.pravega.io_zookeeperclusters.yaml
- pkg/zk/generators.go
Added support for configuring pdb
Also made crds in charts sync with config/crd/bases/crd
Fixes #464
Provide support to configure pdb
All e2e should pass
> Issue 464: Adding support for configuring pdb

- charts/zookeeper-operator/templates/operator.yaml
- config/manager/manager.yaml
- main.go
use the customized leader.Become function as it handles certain pre-checks
Fixes #467
When the operator-sdk version is upgraded, the customized leader function got replaced with operator-lib leader.Become function. So this PR reverts that and use customized function.
Also modifying operator.yaml to fix compatibility issues
All e2e should pass
> Issue 467: Fixing Leader election failure

- README.md
- docker/Dockerfile
- docker/zu/build.gradle.kts
Version 3.8.0 is not stable enough for usage, downgrading to
use 3.7.0.
Fixes: #470
Run `make build-zk-image` and execute e2e tests with newly build image
> Use zookeeper 3.7.0 version

- docker/bin/zookeeperTeardown.sh
Signed-off-by: Nishant Gupta <Nishant_Gupta3@dell.com>
Currently the CONN_COUNT variable is only evaluated once in the zookeeperTeardown.sh script 
As a result, the loop would always take 30 seconds if there were client connections present when the script started to run, and ZK pod would terminate with 137 error code with the default termination grace period set to 30s.  Need to make sure CONN_COUNT gets reevaluated every cycle and allows the code to break out of the loop earlier.
Fixes #482
Moves the CONN_COUNT variable inside the for loop
All e2e should pass
> Issue 482: Reevaluating number of client connections dynamically in the teardown script

- README.md
- docker/Dockerfile
- docker/zu/build.gradle.kts
Signed-off-by: Amit-Singh40 <amit.singh30@dell.com>
Upgraded the zookeeper version to 3.7.1 to fix vulnerabilities in 3.7.0
Fixes #484 
Upgrades the zookeeper to 3.7.1
Perform jenkins tests: Pravega_ZookeeperOperator, Pravega_Zookeeper_Upgrade and Pravega_ZookeeperOperator_E2E and github build.
> upgrading zookeeper to 3.7.1

- pkg/zk/synchronizers.go
- Updating zk.SyncService to update annotations of services
- Fixed #474
- Now service annotations can be configured by user at runtime
Fix #474, now service annotations are not only created but also updated.
We added one line of code in the function to update annotations.
```golang
curr.SetAnnotations(next.GetAnnotations())
```
1. Build the image and deploy the operator
2. Deploy a zookeeper instance with no annotations specified
```YAML
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
name: zookeeper
spec:
replicas: 3
```
3. Execute `kubectl get svc/zookeeper-headless -o yaml` and observe that this service does not have any annotations.
```YAML
apiVersion: v1
kind: Service
metadata:
creationTimestamp: "2022-08-01T21:56:06Z"
labels:
app: zookeeper
headless: …
```
> Fix #474: Svc Annotations created but not updated

- controllers/zookeepercluster_controller.go
- controllers/zookeepercluster_controller_test.go
- pkg/zk/generators.go
- pkg/zk/generators_test.go
Replaces the deprecated PodDistruptionBudget policy/v1beta1 API with the new policy/v1 API.
Closes https://github.com/pravega/zookeeper-operator/issues/428
Replaces the policy/v1beta1 API by simply changing the API version, there are no schema changes to the API, only a behavioral change - see https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125.
A simple verification would be to manually create a ZK cluster on a 1.25 Kubernetes cluster and verify that the PDB created is using the new API. The e2e tests seem to cover this though so those seem to be sufficient.
> feat: Replace deprecated policy/v1beta1 PDB API

- api/v1beta1/deepcopy_test.go
- api/v1beta1/zookeepercluster_types.go
- api/v1beta1/zz_generated.deepcopy.go
- charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- charts/zookeeper/templates/zookeeper.yaml
- charts/zookeeper/values.yaml
- config/crd/bases/zookeeper.pravega.io_zookeeperclusters.yaml
- pkg/zk/generators.go
- pkg/zk/generators_test.go
Adds `topologySpreadConstraints` support to pod deployment definition.
Fixes #427
Adds an existing specification to the Spec.Pod to aid in topology spread.
Add a `topologySpreadConstraints` and see if it shows up in the Zookeeper StatefulSet pod spec.
> Add topologySpreadConstraints to PodSpec

- api/v1beta1/zookeepercluster_types.go
- charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml
- config/crd/bases/zookeeper.pravega.io_zookeeperclusters.yaml
- pkg/zk/generators.go
Pod labels from the Spec.Pod.Labels were previously not propagated to the StatefulSet.Template.
Resolves #511
- Adds the Spec.Pod.Labels to the creation of the StatefulSet template
- Adds docs to note the differences between the two Label locations in the ZookeeperCluster CRD and denotes priority order
- Add labels to the Spec.Pod.Labels and expect to have it show up in the pod labels
> Adjust behavior for pod labels

- charts/zookeeper-operator/templates/pre-delete-hooks.yaml
make delete Job respect scheduling choices
Makes the delete job respect node scheduling the same as the post install hooks do. Without this, it fails in a mixed windows/linux cluster.
Fixes https://github.com/pravega/zookeeper-operator/issues/518
Fixes https://github.com/apache/solr-operator/issues/382
Adds a node selector to control pre-delete Job scheduling
Deploy and remove. See that it schedules where you expect it to.
> Adds nodeSelector, affinity and tolerations to the pre-delete hook Job

- README.md
- docker/Dockerfile
- docker/zu/build.gradle.kts
While running trivy to look for vulnerabilities in the latest 0.2.15 images, the report returned multiple CRITICAL CVEs in the zookeeper image that have been resolved in the latest stable 3.7.2.
Fixes #585.
Upgrade version of Zookeeper to version 3.7.2
> Build validation
make build-zk-image runs succesfully
> Tests executed
ran `make test`
```
go test $(go list ./... | grep -v /vendor/ | grep -v /test/e2e) -race -coverprofile=coverage.txt -covermode=atomic
?   	github.com/pravega/zookeeper-operator	[no test files]
?   	github.com/pravega/zookeeper-operator/cmd/exporter	[no test files]
?   	github.com/pravega/zookeeper-operator/pkg/controller/config	[no test files]
?   	github.com/pravega/zookeeper-operator/pkg/version	[no test files]
ok  	github.com/pravega/zookeeper-operator/api/v1beta1 …
```
> Issue 585: Upgrade Zookeeper to version 3.7.2

- charts/zookeeper-operator/templates/post-install-upgrade-hooks.yaml
- charts/zookeeper-operator/templates/pre-delete-hooks.yaml
- charts/zookeeper-operator/values.yaml
* Adds imagePullSecrets to the service accounts for the Helm hooks
* Follows the same principle as the service account for the operator taking global imagePullSecrets into account
Fixes #589
Adds imagePullSecrets to the YAML for the ServiceAccounts for the Helm hooks. This is important when images are pulled from a private registry, e.g. an internal proxy, such as Artifactory, or when using custom images.
Render the templates using the following command:
```console
helm template zookeeper charts/zookeeper-operator \
--show-only templates/post-install-upgrade-hooks.yaml \
--show-only templates/pre-delete-hooks.yaml \
--set hooks.serviceAccount.imagePullSecrets={'my-pull-secret'}
```
> Issue 589: Add imagePullSecrets for Helm hooks
